before_script:
  - cd /mnt/disks/disk1/if3250_2023_k01_06_dosenrank && git reset --hard && git pull

stages:          # List of stages for jobs, and their order of execution
  - build-deploy

build-deploy-app:       # This job runs in the build stage, which runs first.
  stage: build-deploy
  only:
    - main
  script:
    - yarn
    - yarn global add vercel
    - export PATH=$PATH:~/.yarn/bin
    - vercel pull --yes --token=$VERCEL_TOKEN
    - vercel --prod --token=$VERCEL_TOKEN
  tags:
    - FE
